/**
 * AutoSphere Prototype — Navigation Data
 * Mỗi đối tượng hệ sinh thái = 1 Tenant độc lập
 */

const ACCOUNT_FLOW_PAGES = {
  'Đăng ký tài khoản': '../account/pages/01-dang-ky.html',
  'Đăng nhập': '../account/pages/02-dang-nhap.html',
  'Xác thực OTP': '../account/pages/03-xac-thuc-otp.html',
  'Xác thực định danh': '../account/pages/04-xac-thuc-dinh-danh.html',
  'Cập nhật hồ sơ cá nhân': '../account/pages/05-ho-so-ca-nhan.html',
  'Quản lý giấy tờ cá nhân': '../account/pages/06-giay-to-ca-nhan.html',
  'Quản lý địa chỉ': '../account/pages/07-quan-ly-dia-chi.html',
  'Quản lý thiết bị đăng nhập': '../account/pages/08-thiet-bi-dang-nhap.html',
  'Xóa hoặc khóa tài khoản': '../account/pages/11-khoa-tai-khoan.html',
};

const ORG_MANAGEMENT = [
  'Hồ sơ doanh nghiệp',
  'Quản lý chi nhánh',
  'Quản lý phòng ban',
  'Quản lý nhân viên',
  'Phân quyền',
  'Quản lý giấy phép',
];

const TENANTS = {
  consumer: {
    id: 'consumer',
    label: 'Người dùng dịch vụ',
    shortLabel: 'Chủ xe',
    icon: '👤',
    color: '#3b82f6',
    modules: [
      { id: '01', title: 'Tài khoản cá nhân', items: ['Đăng ký tài khoản', 'Đăng nhập', 'Xác thực OTP', 'Xác thực định danh', 'Cập nhật hồ sơ cá nhân', 'Quản lý giấy tờ cá nhân', 'Quản lý địa chỉ', 'Quản lý thiết bị đăng nhập', 'Xóa hoặc khóa tài khoản'] },
      { id: '02', title: 'Gara cá nhân', items: ['Thêm phương tiện', 'Xác thực phương tiện', 'Quản lý nhiều phương tiện', 'Cập nhật thông tin xe', 'Quản lý giấy tờ xe', 'Quản lý lịch sử sở hữu', 'Theo dõi tình trạng xe', 'Theo dõi giá trị xe', 'Xem hồ sơ kinh tế số của xe'] },
      { id: '03', title: 'Mua xe', items: ['Tìm kiếm xe mới', 'Tìm kiếm xe cũ', 'So sánh xe', 'Xem giá niêm yết', 'Xem ưu đãi đại lý', 'Yêu cầu báo giá', 'Nhận tư vấn mua xe', 'Đăng ký lái thử', 'Giữ chỗ xe', 'Theo dõi tiến trình mua xe'] },
      { id: '04', title: 'Tài chính phương tiện', items: ['Kiểm tra khả năng vay', 'Mô phỏng khoản vay', 'So sánh gói vay', 'Gửi hồ sơ vay', 'Theo dõi xét duyệt', 'Nhận đề xuất tài chính', 'Quản lý khoản vay', 'Nhắc lịch thanh toán', 'Đề xuất tái cấp vốn'] },
      { id: '05', title: 'Bảo hiểm phương tiện', items: ['Xem gói bảo hiểm', 'So sánh bảo hiểm', 'Nhận báo giá bảo hiểm', 'Mua bảo hiểm', 'Gia hạn bảo hiểm', 'Quản lý hợp đồng bảo hiểm', 'Nhắc hết hạn bảo hiểm', 'Khai báo tổn thất', 'Theo dõi bồi thường'] },
      { id: '06', title: 'Bảo dưỡng và sửa chữa', items: ['Xem lịch bảo dưỡng', 'Nhắc bảo dưỡng định kỳ', 'Tìm gara phù hợp', 'So sánh dịch vụ', 'Đặt lịch bảo dưỡng', 'Đặt lịch sửa chữa', 'Theo dõi tiến độ dịch vụ', 'Nhận báo giá sửa chữa', 'Thanh toán dịch vụ', 'Lưu lịch sử bảo dưỡng'] },
      { id: '07', title: 'Cứu hộ và hỗ trợ khẩn cấp', items: ['Gọi cứu hộ', 'Gửi vị trí hiện tại', 'Chọn loại sự cố', 'Theo dõi xe cứu hộ', 'Nhận báo giá cứu hộ', 'Xác nhận hoàn tất cứu hộ', 'Đánh giá dịch vụ cứu hộ'] },
      { id: '08', title: 'Phụ kiện và nâng cấp', items: ['Xem phụ kiện phù hợp với xe', 'Nhận đề xuất nâng cấp', 'So sánh phụ kiện', 'Đặt mua phụ kiện', 'Đặt lịch lắp đặt', 'Theo dõi bảo hành phụ kiện', 'Lưu lịch sử nâng cấp xe'] },
      { id: '09', title: 'Bán hoặc chuyển nhượng xe', items: ['Yêu cầu định giá xe', 'Xem giá trị thị trường', 'Tạo tin bán xe', 'Nhận người mua quan tâm', 'Nhận đề xuất thu mua', 'Quản lý đàm phán', 'Xác minh lịch sử xe', 'Chuyển quyền sở hữu', 'Cập nhật hồ sơ xe sau chuyển nhượng'] },
      { id: '10', title: 'Dữ liệu và quyền riêng tư', items: ['Xem dữ liệu cá nhân', 'Xem dữ liệu phương tiện', 'Quản lý quyền chia sẻ dữ liệu', 'Cấp quyền cho đối tác', 'Thu hồi quyền truy cập', 'Xem lịch sử truy cập dữ liệu', 'Yêu cầu xóa dữ liệu'] },
      { id: '11', title: 'Thanh toán và hóa đơn', items: ['Quản lý phương thức thanh toán', 'Thanh toán dịch vụ', 'Thanh toán đặt cọc', 'Thanh toán bảo hiểm', 'Thanh toán bảo dưỡng', 'Xem lịch sử giao dịch', 'Tải hóa đơn', 'Theo dõi hoàn tiền'] },
      { id: '12', title: 'Ưu đãi và thành viên', items: ['Xem điểm thưởng', 'Xem hạng thành viên', 'Nhận mã ưu đãi', 'Sử dụng ưu đãi', 'Giới thiệu bạn bè', 'Theo dõi hoa hồng giới thiệu', 'Nhận ưu đãi theo xe'] },
      { id: '13', title: 'Trợ lý AI cá nhân', items: ['Tư vấn mua xe', 'Tư vấn tài chính', 'Tư vấn bảo hiểm', 'Nhắc bảo dưỡng', 'Dự báo chi phí sử dụng xe', 'Cảnh báo rủi ro phương tiện', 'Đề xuất gara', 'Đề xuất thời điểm bán xe', 'Quản lý vòng đời phương tiện'] },
      { id: '14', title: 'Thông báo và chăm sóc', items: ['Thông báo mua xe', 'Thông báo tài chính', 'Thông báo bảo hiểm', 'Thông báo bảo dưỡng', 'Thông báo đăng kiểm', 'Thông báo ưu đãi', 'Gửi yêu cầu hỗ trợ', 'Theo dõi yêu cầu hỗ trợ', 'Đánh giá dịch vụ'] },
    ],
  },

  dealer: {
    id: 'dealer',
    label: 'Đại lý / Showroom',
    shortLabel: 'Đại lý',
    icon: '🏪',
    color: '#8b5cf6',
    modules: [
      { id: '01', title: 'Quản lý tổ chức', items: ['Hồ sơ đại lý', 'Quản lý chi nhánh', 'Quản lý phòng ban', 'Quản lý nhân viên', 'Phân quyền', 'Quản lý giấy phép'] },
      { id: '02', title: 'Quản lý xe', items: ['Danh mục xe OEM', 'Xe tồn kho', 'Xe đang vận chuyển', 'Xe trưng bày', 'Xe lái thử', 'Xe ký gửi', 'Xe đã bán', 'Xe đã thu mua'] },
      { id: '03', title: 'Quản lý báo giá', items: ['Tạo báo giá', 'Chỉnh sửa báo giá', 'Phiên bản báo giá', 'Chính sách giảm giá', 'Khuyến mại', 'Báo giá tài chính', 'Báo giá bảo hiểm', 'Báo giá tổng hợp'] },
      { id: '04', title: 'Quản lý khách hàng', items: ['Danh sách khách hàng', 'Phân nhóm khách hàng', 'Nhu cầu mua xe', 'Theo dõi lịch sử giao dịch', 'Quản lý hồ sơ tài chính', 'Quản lý bảo hiểm', 'Ghi chú chăm sóc', 'Lịch sử tương tác'] },
      { id: '05', title: 'Quản lý cơ hội bán hàng', items: ['Lead mới', 'Lead từ OEM', 'Lead từ AutoSphere', 'Lead từ Affiliate', 'Giao lead', 'Chuyển trạng thái lead', 'Chấm điểm lead', 'Dự báo doanh số'] },
      { id: '06', title: 'Bán xe', items: ['Tạo đơn hàng', 'Đặt cọc', 'Ký hợp đồng', 'Yêu cầu giải ngân', 'Yêu cầu bảo hiểm', 'Theo dõi giao xe', 'Bàn giao xe', 'Hoàn tất giao dịch'] },
      { id: '07', title: 'Thu mua xe cũ', items: ['Tiếp nhận yêu cầu', 'Định giá xe', 'Kiểm tra lịch sử xe', 'Đề xuất giá mua', 'Ký hợp đồng mua lại', 'Chuyển sở hữu', 'Đưa xe vào tồn kho'] },
      { id: '08', title: 'Lái thử', items: ['Đăng ký lái thử', 'Sắp lịch lái thử', 'Phân công xe', 'Phân công nhân viên', 'Xác nhận lịch', 'Thu thập đánh giá', 'Chuyển đổi thành cơ hội bán hàng'] },
      { id: '09', title: 'Tài chính', items: ['Gửi hồ sơ vay', 'So sánh ngân hàng', 'Theo dõi xét duyệt', 'Theo dõi giải ngân', 'Hoa hồng tài chính', 'Báo cáo tài chính'] },
      { id: '10', title: 'Bảo hiểm', items: ['Gửi yêu cầu báo giá', 'So sánh bảo hiểm', 'Chọn gói bảo hiểm', 'Phát hành hợp đồng', 'Gia hạn bảo hiểm', 'Hoa hồng bảo hiểm'] },
      { id: '11', title: 'Hậu mãi', items: ['Theo dõi bảo hành', 'Nhắc bảo dưỡng', 'Đặt lịch dịch vụ', 'Chăm sóc khách hàng', 'Quản lý khiếu nại'] },
      { id: '12', title: 'Tiếp thị', items: ['Quản lý chiến dịch', 'Email Marketing', 'SMS Marketing', 'Zalo Marketing', 'Facebook Leads', 'TikTok Leads', 'Affiliate Marketing'] },
      { id: '13', title: 'Trợ lý AI', items: ['AI đề xuất khách hàng', 'AI dự báo doanh số', 'AI đề xuất giá bán', 'AI tư vấn tài chính', 'AI chăm sóc khách hàng', 'AI nhắc tái mua', 'AI phân tích thị trường'] },
      { id: '14', title: 'Báo cáo', items: ['Doanh số', 'Hiệu suất nhân viên', 'Hiệu suất chiến dịch', 'Tỷ lệ chuyển đổi', 'Doanh thu tài chính', 'Doanh thu bảo hiểm', 'Doanh thu hậu mãi', 'Tổng lợi nhuận khách hàng'] },
    ],
  },

  oem: {
    id: 'oem',
    label: 'OEM / Hãng xe',
    shortLabel: 'OEM',
    icon: '🏭',
    color: '#0ea5e9',
    modules: [
      { id: '01', title: 'Quản lý tổ chức OEM', items: ['Hồ sơ doanh nghiệp', 'Quản lý thương hiệu', 'Quản lý công ty thành viên', 'Quản lý quốc gia hoạt động', 'Quản lý thị trường', 'Quản lý người dùng nội bộ', 'Phân quyền', 'Quản lý đối tác OEM'] },
      { id: '02', title: 'Quản lý danh mục sản phẩm', items: ['Quản lý dòng xe', 'Quản lý phiên bản xe', 'Quản lý đời xe', 'Quản lý cấu hình', 'Quản lý màu sắc', 'Quản lý phụ kiện chính hãng', 'Quản lý gói tùy chọn', 'Quản lý thông số kỹ thuật', 'Quản lý tài liệu sản phẩm'] },
      { id: '03', title: 'Quản lý giá bán', items: ['Giá niêm yết', 'Giá theo quốc gia', 'Giá theo đại lý', 'Chính sách giảm giá', 'Chính sách khuyến mại', 'Chương trình ưu đãi', 'Quản lý thời gian hiệu lực', 'Lịch sử thay đổi giá'] },
      { id: '04', title: 'Quản lý mạng lưới đại lý', items: ['Danh sách đại lý', 'Hồ sơ đại lý', 'Phê duyệt đại lý', 'Xếp hạng đại lý', 'Đánh giá hiệu suất', 'Chỉ tiêu doanh số', 'Chính sách thưởng', 'Theo dõi tồn kho đại lý', 'Theo dõi hoạt động bán hàng'] },
      { id: '05', title: 'Quản lý phương tiện đã bán', items: ['Danh sách phương tiện lưu hành', 'Theo dõi VIN', 'Theo dõi chủ sở hữu', 'Theo dõi khu vực sử dụng', 'Theo dõi vòng đời xe', 'Theo dõi lịch sử bảo hành', 'Theo dõi bảo dưỡng', 'Theo dõi sửa chữa', 'Theo dõi chuyển nhượng'] },
      { id: '06', title: 'Quản lý bảo hành', items: ['Chính sách bảo hành', 'Kích hoạt bảo hành', 'Gia hạn bảo hành', 'Tiếp nhận yêu cầu bảo hành', 'Phê duyệt bảo hành', 'Từ chối bảo hành', 'Theo dõi chi phí bảo hành', 'Thống kê lỗi bảo hành'] },
      { id: '07', title: 'Quản lý triệu hồi', items: ['Tạo chiến dịch triệu hồi', 'Xác định VIN bị ảnh hưởng', 'Gửi thông báo triệu hồi', 'Theo dõi tiến độ xử lý', 'Xác nhận hoàn thành', 'Báo cáo triệu hồi'] },
      { id: '08', title: 'Quản lý dữ liệu phương tiện', items: ['Hồ sơ kinh tế số phương tiện', 'Theo dõi giá trị còn lại', 'Theo dõi tỷ lệ giữ giá', 'Theo dõi chi phí sở hữu', 'Theo dõi hành vi sử dụng', 'Theo dõi dữ liệu pin EV', 'Theo dõi dữ liệu IoT', 'Theo dõi Vehicle Economic Profile'] },
      { id: '09', title: 'Quản lý chương trình khách hàng', items: ['Chương trình thành viên', 'Điểm thưởng', 'Ưu đãi nâng cấp xe', 'Ưu đãi phụ kiện', 'Ưu đãi dịch vụ', 'Chiến dịch tái mua', 'Chiến dịch giữ chân khách hàng'] },
      { id: '10', title: 'Quản lý đối tác tài chính', items: ['Danh sách ngân hàng', 'Chính sách tài trợ', 'Gói vay OEM', 'Chương trình hỗ trợ lãi suất', 'Theo dõi giải ngân', 'Đánh giá hiệu suất ngân hàng'] },
      { id: '11', title: 'Quản lý đối tác bảo hiểm', items: ['Danh sách bảo hiểm', 'Gói bảo hiểm OEM', 'Chính sách hợp tác', 'Theo dõi doanh thu bảo hiểm', 'Theo dõi tỷ lệ tái tục', 'Đánh giá hiệu suất bảo hiểm'] },
      { id: '12', title: 'Quản lý OTA và xe kết nối', items: ['Quản lý thiết bị OBD', 'Quản lý Telematics', 'Quản lý pin EV', 'Cập nhật OTA', 'Theo dõi trạng thái cập nhật', 'Phân phối tính năng mới', 'Mở khóa tính năng từ xa', 'Thu phí tính năng số'] },
      { id: '13', title: 'Quản lý hệ sinh thái ứng dụng', items: ['Chợ ứng dụng OEM', 'Cài đặt ứng dụng', 'Gỡ ứng dụng', 'Phê duyệt ứng dụng', 'Chia sẻ doanh thu', 'Quản lý API OEM', 'Quản lý SDK OEM'] },
      { id: '14', title: 'Trợ lý AI OEM', items: ['AI dự báo doanh số', 'AI dự báo nhu cầu thị trường', 'AI dự báo lỗi kỹ thuật', 'AI dự báo triệu hồi', 'AI đề xuất chính sách giá', 'AI đề xuất khuyến mại', 'AI đánh giá hiệu suất đại lý', 'AI phân tích vòng đời khách hàng'] },
      { id: '15', title: 'Báo cáo điều hành OEM', items: ['Báo cáo doanh số', 'Báo cáo tồn kho', 'Báo cáo bảo hành', 'Báo cáo triệu hồi', 'Báo cáo tài chính', 'Báo cáo bảo hiểm', 'Báo cáo giá trị vòng đời khách hàng', 'Báo cáo Vehicle Economy', 'Báo cáo AI Insight'] },
    ],
  },

  bank: {
    id: 'bank',
    label: 'Ngân hàng',
    shortLabel: 'Ngân hàng',
    icon: '🏦',
    color: '#059669',
    modules: [
      { id: '01', title: 'Quản lý tổ chức', items: ['Hồ sơ ngân hàng', 'Quản lý chi nhánh', 'Quản lý nhân viên', 'Phân quyền', 'Quản lý giấy phép'] },
      { id: '02', title: 'Quản lý sản phẩm tài chính', items: ['Gói vay mua xe', 'Gói thuê tài chính', 'Gói tái cấp vốn', 'Chính sách lãi suất', 'Chương trình ưu đãi', 'Điều kiện vay'] },
      { id: '03', title: 'Tiếp nhận hồ sơ vay', items: ['Hồ sơ từ khách hàng', 'Hồ sơ từ đại lý', 'Hồ sơ từ OEM', 'Kiểm tra hồ sơ', 'Yêu cầu bổ sung'] },
      { id: '04', title: 'Xét duyệt tín dụng', items: ['Chấm điểm tín dụng', 'Định giá tài sản', 'Kiểm tra CIC', 'Đánh giá rủi ro', 'Phê duyệt khoản vay'] },
      { id: '05', title: 'Giải ngân', items: ['Ký hợp đồng điện tử', 'Giải ngân', 'Theo dõi khoản vay', 'Thu nợ', 'Tất toán'] },
      { id: '06', title: 'Quản lý đối tác', items: ['Danh sách đại lý', 'Danh sách OEM', 'Chính sách hoa hồng', 'Theo dõi hiệu suất đối tác', 'Quản lý hợp đồng hợp tác'] },
      { id: '07', title: 'Quản lý khách hàng', items: ['Hồ sơ khách hàng vay', 'Lịch sử tín dụng', 'Phân loại rủi ro', 'Nhắc thanh toán', 'Chăm sóc khách hàng'] },
      { id: '08', title: 'Leasing & Tái cấp vốn', items: ['Quản lý hợp đồng thuê tài chính', 'Tính giá trị còn lại', 'Xử lý tái cấp vốn', 'Mua lại tài sản', 'Chuyển nhượng hợp đồng'] },
      { id: '09', title: 'Tuân thủ & pháp lý', items: ['Báo cáo NHNN', 'Quản lý hợp đồng', 'Lưu trữ hồ sơ', 'Kiểm toán nội bộ', 'Quản lý rủi ro tuân thủ'] },
      { id: '10', title: 'Marketing tài chính', items: ['Chiến dịch ưu đãi lãi suất', 'Gói vay theo dòng xe', 'Landing page sản phẩm', 'Lead từ AutoSphere', 'Affiliate finance'] },
      { id: '11', title: 'Thanh toán & đối soát', items: ['Giải ngân đại lý', 'Thu nợ tự động', 'Đối soát giao dịch', 'Hoa hồng đại lý', 'Báo cáo doanh thu lãi'] },
      { id: '12', title: 'AI Agent Ngân hàng', items: ['AI chấm điểm tín dụng', 'AI đánh giá rủi ro', 'AI đề xuất gói vay', 'AI dự báo nợ xấu', 'AI tư vấn khách hàng', 'AI phân tích danh mục'] },
      { id: '13', title: 'Dashboard tài chính', items: ['Tổng quan khoản vay', 'Pipeline hồ sơ', 'Tỷ lệ phê duyệt', 'Doanh số giải ngân', 'NPL & rủi ro', 'Hiệu suất chi nhánh', 'Báo cáo đối tác'] },
    ],
  },

  insurance: {
    id: 'insurance',
    label: 'Công ty bảo hiểm',
    shortLabel: 'Bảo hiểm',
    icon: '🛡️',
    color: '#d97706',
    modules: [
      { id: '01', title: 'Quản lý tổ chức', items: ['Hồ sơ công ty bảo hiểm', 'Quản lý chi nhánh', 'Quản lý nhân viên', 'Phân quyền', 'Quản lý giấy phép'] },
      { id: '02', title: 'Quản lý sản phẩm bảo hiểm', items: ['Bảo hiểm vật chất', 'Bảo hiểm TNDS', 'Bảo hiểm pin EV', 'Bảo hiểm phụ kiện', 'Bảo hiểm mở rộng'] },
      { id: '03', title: 'Báo giá bảo hiểm', items: ['Tạo báo giá', 'Báo giá tự động', 'So sánh gói', 'Báo giá theo xe', 'Báo giá theo hành vi'] },
      { id: '04', title: 'Quản lý hợp đồng', items: ['Phát hành', 'Gia hạn', 'Hủy hợp đồng', 'Theo dõi hiệu lực'] },
      { id: '05', title: 'Bồi thường', items: ['Tiếp nhận tổn thất', 'Giám định', 'Duyệt bồi thường', 'Thanh toán'] },
      { id: '06', title: 'Risk Engine', items: ['Mô hình rủi ro', 'Phân loại rủi ro xe', 'Phân loại rủi ro tài xế', 'Pricing theo rủi ro', 'Fraud detection'] },
      { id: '07', title: 'Usage Based Insurance', items: ['Thu thập dữ liệu hành trình', 'Tính phí theo km', 'Tính phí theo hành vi', 'Dashboard UBI', 'Điều chỉnh phí định kỳ'] },
      { id: '08', title: 'Quản lý đối tác', items: ['Đại lý bảo hiểm', 'Đối tác OEM', 'Đối tác gara giám định', 'Hoa hồng', 'Theo dõi hiệu suất'] },
      { id: '09', title: 'Quản lý khách hàng', items: ['Hồ sơ khách hàng', 'Lịch sử bồi thường', 'Nhắc gia hạn', 'Chăm sóc khách hàng', 'Phân nhóm khách hàng'] },
      { id: '10', title: 'Gia hạn & tái tục', items: ['Danh sách sắp hết hạn', 'Gia hạn tự động', 'Chiến dịch tái tục', 'Theo dõi tỷ lệ tái tục', 'Ưu đãi gia hạn'] },
      { id: '11', title: 'Tuân thủ & pháp lý', items: ['Báo cáo cơ quan quản lý', 'Quản lý hợp đồng', 'Lưu trữ hồ sơ', 'Kiểm toán nội bộ'] },
      { id: '12', title: 'AI Agent Bảo hiểm', items: ['AI báo giá', 'AI đánh giá rủi ro', 'AI phát hiện gian lận', 'AI dự báo tổn thất', 'AI tư vấn gói bảo hiểm', 'AI tối ưu tái tục'] },
      { id: '13', title: 'Dashboard', items: ['Tổng quan doanh thu', 'Tỷ lệ bồi thường', 'Pipeline hợp đồng', 'Hiệu suất đại lý', 'Phân tích rủi ro', 'Báo cáo UBI'] },
    ],
  },

  service: {
    id: 'service',
    label: 'Gara / Trung tâm dịch vụ',
    shortLabel: 'Gara',
    icon: '🔧',
    color: '#6366f1',
    modules: [
      { id: '01', title: 'Quản lý tổ chức', items: ['Hồ sơ gara', 'Quản lý chi nhánh', 'Quản lý nhân viên', 'Phân quyền', 'Quản lý giấy phép', 'Giờ làm việc & ca trực'] },
      { id: '02', title: 'Quản lý kỹ thuật viên', items: ['Danh sách kỹ thuật viên', 'Chuyên môn & chứng chỉ', 'Phân công ca', 'Đánh giá hiệu suất', 'Lịch làm việc'] },
      { id: '03', title: 'Quản lý dịch vụ', items: ['Bảo dưỡng', 'Sửa chữa', 'Đồng sơn', 'Chăm sóc xe', 'Kiểm định'] },
      { id: '04', title: 'Đặt lịch dịch vụ', items: ['Lịch hẹn', 'Xác nhận lịch', 'Nhắc lịch khách hàng', 'Hủy / đổi lịch', 'Lịch theo bay'] },
      { id: '05', title: 'Work Order', items: ['Tiếp nhận xe', 'Chuẩn đoán lỗi', 'Báo giá', 'Thực hiện', 'Bàn giao'] },
      { id: '06', title: 'Quản lý phụ tùng', items: ['Danh mục phụ tùng', 'Tồn kho', 'Nhập / xuất kho', 'Đặt hàng NCC', 'Tra cứu tương thích'] },
      { id: '07', title: 'Quản lý bảo hành', items: ['Bảo hành hãng', 'Bảo hành gara', 'Tiếp nhận yêu cầu BH', 'Phê duyệt bảo hành', 'Theo dõi chi phí BH'] },
      { id: '08', title: 'Quản lý khách hàng', items: ['Hồ sơ khách hàng', 'Lịch sử dịch vụ', 'Xe đang sửa', 'Chăm sóc khách hàng', 'Đánh giá dịch vụ'] },
      { id: '09', title: 'Thanh toán & hóa đơn', items: ['Báo giá dịch vụ', 'Thanh toán', 'Xuất hóa đơn', 'Đối soát', 'Hoàn tiền'] },
      { id: '10', title: 'Đối tác & hoa hồng', items: ['Đối tác phụ tùng', 'Đối tác bảo hiểm', 'Lead từ AutoSphere', 'Affiliate', 'Hoa hồng'] },
      { id: '11', title: 'AI Service Agent', items: ['AI chuẩn đoán lỗi', 'AI đề xuất dịch vụ', 'AI dự báo bảo dưỡng', 'AI tối ưu lịch', 'AI đề xuất phụ tùng', 'AI phân tích doanh thu'] },
      { id: '12', title: 'Dashboard', items: ['Doanh thu dịch vụ', 'Work order đang xử lý', 'Hiệu suất kỹ thuật viên', 'Tỷ lệ quay lại', 'Tồn kho phụ tùng', 'Đánh giá khách hàng'] },
    ],
  },

  accessory: {
    id: 'accessory',
    label: 'Nhà cung cấp phụ kiện',
    shortLabel: 'Phụ kiện',
    icon: '📦',
    color: '#ec4899',
    modules: [
      { id: '01', title: 'Quản lý doanh nghiệp', items: ['Hồ sơ doanh nghiệp', 'Quản lý chi nhánh', 'Quản lý nhân viên', 'Phân quyền', 'Quản lý giấy phép'] },
      { id: '02', title: 'Danh mục sản phẩm', items: ['Danh mục phụ kiện', 'Tương thích dòng xe', 'Thông số sản phẩm', 'Hình ảnh & tài liệu', 'Giá bán & giá sỉ'] },
      { id: '03', title: 'Tồn kho', items: ['Tồn kho theo SKU', 'Nhập / xuất kho', 'Cảnh báo hết hàng', 'Kiểm kê', 'Đa kho'] },
      { id: '04', title: 'Đơn hàng', items: ['Đơn hàng mới', 'Xử lý đơn', 'Giao hàng', 'Hoàn trả', 'Theo dõi vận chuyển'] },
      { id: '05', title: 'Lắp đặt', items: ['Đặt lịch lắp đặt', 'Phân công kỹ thuật viên', 'Theo dõi tiến độ', 'Nghiệm thu', 'Đánh giá lắp đặt'] },
      { id: '06', title: 'Bảo hành', items: ['Chính sách bảo hành', 'Kích hoạt bảo hành', 'Tiếp nhận bảo hành', 'Xử lý bảo hành', 'Thống kê bảo hành'] },
      { id: '07', title: 'Affiliate Sales', items: ['Đối tác affiliate', 'Link giới thiệu', 'Theo dõi chuyển đổi', 'Hoa hồng', 'Chiến dịch'] },
      { id: '08', title: 'Marketplace', items: ['Listing sản phẩm', 'Quản lý ưu đãi', 'Đánh giá sản phẩm', 'Flash sale', 'Cross-sell theo xe'] },
      { id: '09', title: 'Quản lý khách hàng', items: ['Hồ sơ khách hàng', 'Lịch sử mua hàng', 'Chăm sóc khách hàng', 'Phân nhóm', 'Chương trình thành viên'] },
      { id: '10', title: 'AI Sales Agent', items: ['AI đề xuất phụ kiện', 'AI cross-sell', 'AI dự báo nhu cầu', 'AI tối ưu giá', 'AI chăm sóc khách hàng'] },
      { id: '11', title: 'Dashboard', items: ['Doanh thu', 'Đơn hàng', 'Tồn kho', 'Hiệu suất affiliate', 'Top sản phẩm', 'Tỷ lệ lắp đặt'] },
    ],
  },

  rescue: {
    id: 'rescue',
    label: 'Đơn vị cứu hộ',
    shortLabel: 'Cứu hộ',
    icon: '🚑',
    color: '#ef4444',
    modules: [
      { id: '01', title: 'Quản lý tổ chức', items: ['Hồ sơ đơn vị cứu hộ', 'Quản lý trạm', 'Quản lý nhân viên', 'Phân quyền', 'Quản lý giấy phép', 'Khu vực phục vụ'] },
      { id: '02', title: 'Quản lý phương tiện cứu hộ', items: ['Danh sách xe cứu hộ', 'Trạng thái xe', 'Bảo dưỡng xe cứu hộ', 'Theo dõi vị trí', 'Thiết bị trên xe'] },
      { id: '03', title: 'Quản lý tài xế', items: ['Danh sách tài xế', 'Ca trực', 'Vị trí realtime', 'Đánh giá hiệu suất', 'Chứng chỉ & đào tạo'] },
      { id: '04', title: 'Điều phối cứu hộ', items: ['Nhận yêu cầu', 'Định vị', 'Phân công', 'Theo dõi', 'Hoàn thành'] },
      { id: '05', title: 'Báo giá cứu hộ', items: ['Bảng giá dịch vụ', 'Báo giá theo khoảng cách', 'Báo giá theo loại sự cố', 'Phê duyệt báo giá', 'Lịch sử báo giá'] },
      { id: '06', title: 'Thanh toán', items: ['Thanh toán khách hàng', 'Thanh toán bảo hiểm', 'Đối soát', 'Hóa đơn', 'Hoàn tiền'] },
      { id: '07', title: 'Quản lý hợp đồng', items: ['Hợp đồng B2B', 'Hợp đồng bảo hiểm', 'Hợp đồng OEM', 'SLA', 'Theo dõi hiệu lực'] },
      { id: '08', title: 'AI Dispatch Agent', items: ['AI phân công tối ưu', 'AI dự báo nhu cầu', 'AI ước tính thời gian', 'AI đề xuất tuyến', 'AI phân tích hiệu suất'] },
      { id: '09', title: 'Dashboard', items: ['Yêu cầu đang xử lý', 'Thời gian phản hồi', 'Doanh thu', 'Hiệu suất tài xế', 'Phân bố khu vực', 'Đánh giá dịch vụ'] },
    ],
  },

  fleet: {
    id: 'fleet',
    label: 'Doanh nghiệp đội xe',
    shortLabel: 'Đội xe',
    icon: '🚛',
    color: '#14b8a6',
    modules: [
      { id: '01', title: 'Quản lý doanh nghiệp', items: ['Hồ sơ doanh nghiệp', 'Quản lý chi nhánh', 'Quản lý nhân viên', 'Phân quyền', 'Quản lý giấy phép'] },
      { id: '02', title: 'Quản lý đội xe', items: ['Danh sách phương tiện', 'Phân loại đội xe', 'Trạng thái xe', 'Đăng kiểm', 'Giấy tờ phương tiện'] },
      { id: '03', title: 'Quản lý tài xế', items: ['Danh sách tài xế', 'Phân công xe', 'Giấy phép lái xe', 'Đánh giá tài xế', 'Ca làm việc'] },
      { id: '04', title: 'Quản lý hành trình', items: ['Lịch trình', 'Theo dõi GPS', 'Lịch sử hành trình', 'Cảnh báo lệch tuyến', 'Báo cáo km'] },
      { id: '05', title: 'Quản lý nhiên liệu', items: ['Theo dõi tiêu thụ', 'Đổ nhiên liệu', 'Phân tích hiệu suất', 'Cảnh báo bất thường', 'Báo cáo chi phí NL'] },
      { id: '06', title: 'Quản lý bảo dưỡng', items: ['Lịch bảo dưỡng', 'Nhắc bảo dưỡng', 'Work order', 'Chi phí bảo dưỡng', 'Lịch sử sửa chữa'] },
      { id: '07', title: 'Quản lý bảo hiểm', items: ['Hợp đồng bảo hiểm', 'Nhắc gia hạn', 'Khai báo tổn thất', 'Theo dõi bồi thường'] },
      { id: '08', title: 'Quản lý chi phí', items: ['TCO theo xe', 'Phân bổ chi phí', 'Ngân sách', 'Báo cáo chi phí', 'So sánh hiệu suất'] },
      { id: '09', title: 'Telematics', items: ['Dữ liệu OBD', 'CANBUS', 'EV Battery', 'Cảnh báo sự cố', 'Hành vi lái xe'] },
      { id: '10', title: 'Tuân thủ & an toàn', items: ['Giờ lái xe', 'Vi phạm giao thông', 'Kiểm tra an toàn', 'Đào tạo tài xế', 'Báo cáo sự cố'] },
      { id: '11', title: 'AI Fleet Agent', items: ['AI tối ưu tuyến', 'AI dự báo bảo dưỡng', 'AI phân tích nhiên liệu', 'AI đề xuất thay xe', 'AI quản lý rủi ro', 'AI tối ưu chi phí'] },
      { id: '12', title: 'Dashboard', items: ['Tổng quan đội xe', 'Chi phí vận hành', 'Hiệu suất tài xế', 'Trạng thái phương tiện', 'Cảnh báo', 'Báo cáo TCO'] },
    ],
  },

  developer: {
    id: 'developer',
    label: 'Nhà phát triển ứng dụng',
    shortLabel: 'Developer',
    icon: '💻',
    color: '#64748b',
    modules: [
      { id: '01', title: 'Hồ sơ nhà phát triển', items: ['Thông tin công ty', 'Team members', 'Xác minh tài khoản', 'Hợp đồng developer', 'Billing profile'] },
      { id: '02', title: 'API Management', items: ['API Keys', 'OAuth Apps', 'Rate limits', 'API Usage', 'API Documentation'] },
      { id: '03', title: 'SDK', items: ['SDK Downloads', 'Integration guides', 'Code samples', 'Changelog', 'Version management'] },
      { id: '04', title: 'Sandbox', items: ['Sandbox environment', 'Test data', 'Mock vehicles', 'Mock transactions', 'Debug logs'] },
      { id: '05', title: 'Webhook', items: ['Webhook endpoints', 'Event subscriptions', 'Delivery logs', 'Retry policy', 'Signature verification'] },
      { id: '06', title: 'Ứng dụng', items: ['My Apps', 'Create App', 'App settings', 'Permissions', 'App analytics'] },
      { id: '07', title: 'Kiểm duyệt ứng dụng', items: ['Submit for review', 'Review status', 'Compliance checklist', 'Security scan', 'Publish history'] },
      { id: '08', title: 'Marketplace', items: ['App listing', 'Pricing', 'Reviews', 'Downloads', 'Featured apps'] },
      { id: '09', title: 'Revenue Sharing', items: ['Revenue dashboard', 'Payout history', 'Commission rules', 'Tax documents', 'Settlement reports'] },
      { id: '10', title: 'Support & Docs', items: ['Developer docs', 'API reference', 'Community forum', 'Support tickets', 'Status page'] },
      { id: '11', title: 'Dashboard', items: ['API calls', 'Active users', 'Revenue', 'App performance', 'Error rates', 'Integration health'] },
    ],
  },

  affiliate: {
    id: 'affiliate',
    label: 'Đối tác tiếp thị liên kết',
    shortLabel: 'Affiliate',
    icon: '📣',
    color: '#f59e0b',
    modules: [
      { id: '01', title: 'Hồ sơ đối tác', items: ['Thông tin đối tác', 'Xác minh tài khoản', 'Hợp đồng affiliate', 'Thông tin thanh toán', 'Kênh marketing'] },
      { id: '02', title: 'Chiến dịch', items: ['Danh sách chiến dịch', 'Tham gia chiến dịch', 'Creative assets', 'Promo codes', 'Campaign performance'] },
      { id: '03', title: 'Link giới thiệu', items: ['Tạo link', 'Deep links', 'QR codes', 'UTM tracking', 'Link analytics'] },
      { id: '04', title: 'Landing Page', items: ['Page builder', 'Templates', 'A/B testing', 'Conversion tracking', 'Custom domains'] },
      { id: '05', title: 'Lead Management', items: ['Lead inbox', 'Lead status', 'Lead scoring', 'Assign to dealer', 'Lead history'] },
      { id: '06', title: 'Theo dõi chuyển đổi', items: ['Clicks', 'Leads', 'Conversions', 'Attribution', 'Funnel analysis'] },
      { id: '07', title: 'Hoa hồng', items: ['Commission rules', 'Pending commissions', 'Approved commissions', 'Commission history', 'Tier rewards'] },
      { id: '08', title: 'Thanh toán', items: ['Payout schedule', 'Payout history', 'Invoice', 'Tax forms', 'Payment methods'] },
      { id: '09', title: 'Marketing tools', items: ['Email templates', 'Social sharing', 'Banner ads', 'Content library', 'Influencer kit'] },
      { id: '10', title: 'AI Marketing Agent', items: ['AI đề xuất chiến dịch', 'AI tối ưu landing page', 'AI viết content', 'AI phân tích audience', 'AI dự báo conversion'] },
      { id: '11', title: 'Dashboard', items: ['Tổng quan hiệu suất', 'Doanh thu hoa hồng', 'Top campaigns', 'Conversion rate', 'ROI', 'Ranking affiliate'] },
    ],
  },

  admin: {
    id: 'admin',
    label: 'Quản trị viên AutoSphere',
    shortLabel: 'Admin',
    icon: '⚙️',
    color: '#1e293b',
    modules: [
      { id: '01', title: 'User Management', items: ['Danh sách người dùng', 'Tạo / sửa user', 'Khóa tài khoản', 'Reset password', 'Session management'] },
      { id: '02', title: 'Organization Management', items: ['Danh sách tổ chức', 'Phê duyệt tổ chức', 'Hồ sơ tổ chức', 'Trạng thái hoạt động', 'Phân loại tổ chức'] },
      { id: '03', title: 'Tenant Management', items: ['Danh sách tenant', 'Cấu hình tenant', 'Theme & domain', 'Chính sách tenant', 'Provisioning'] },
      { id: '04', title: 'Vehicle Registry', items: ['Registry toàn hệ sinh thái', 'VIN lookup', 'Vehicle identity', 'Ownership history', 'Economic profile'] },
      { id: '05', title: 'Marketplace Governance', items: ['Duyệt listing', 'Quản lý danh mục', 'Chính sách marketplace', 'Dispute resolution', 'Quality control'] },
      { id: '06', title: 'Commission Management', items: ['Quy tắc hoa hồng', 'Commission tiers', 'Override rules', 'Commission reports', 'Dispute commissions'] },
      { id: '07', title: 'Payment Settlement', items: ['Settlement batches', 'Partner payouts', 'Reconciliation', 'Failed payments', 'Settlement reports'] },
      { id: '08', title: 'AI Governance', items: ['AI model registry', 'Agent permissions', 'Prompt management', 'AI audit log', 'Bias monitoring'] },
      { id: '09', title: 'Security Center', items: ['Security policies', 'Threat monitoring', 'Access logs', 'Vulnerability scan', 'Incident response'] },
      { id: '10', title: 'Audit Log', items: ['System audit', 'User activity', 'Data access log', 'Config changes', 'Export logs'] },
      { id: '11', title: 'CMS', items: ['Pages', 'Blog / News', 'Banners', 'Notifications', 'Localization'] },
      { id: '12', title: 'Dashboard điều hành', items: ['GMV', 'Active users', 'Active vehicles', 'Revenue', 'Partner performance', 'Platform health', 'Growth metrics'] },
    ],
  },

  investor: {
    id: 'investor',
    label: 'Nhà đầu tư / Cổ đông',
    shortLabel: 'Investor',
    icon: '📈',
    color: '#7c3aed',
    modules: [
      { id: '01', title: 'Hồ sơ nhà đầu tư', items: ['Thông tin nhà đầu tư', 'Xác minh danh tính', 'NDA & agreements', 'Access permissions', 'Communication preferences'] },
      { id: '02', title: 'Danh mục đầu tư', items: ['Portfolio overview', 'Cap table', 'Investment rounds', 'Valuation history', 'Dilution analysis'] },
      { id: '03', title: 'Theo dõi doanh thu', items: ['Revenue breakdown', 'Revenue by segment', 'MRR / ARR', 'Growth rate', 'Revenue forecast'] },
      { id: '04', title: 'Theo dõi GMV', items: ['GMV total', 'GMV by marketplace', 'GMV by tenant type', 'Take rate', 'GMV trend'] },
      { id: '05', title: 'Theo dõi số lượng phương tiện', items: ['Registered vehicles', 'Connected vehicles', 'Active vehicles', 'Vehicle growth', 'By OEM / region'] },
      { id: '06', title: 'Theo dõi tăng trưởng người dùng', items: ['Total users', 'MAU / DAU', 'User by segment', 'Retention', 'Churn rate'] },
      { id: '07', title: 'Theo dõi hiệu suất đối tác', items: ['Partner count', 'Partner revenue', 'Top partners', 'Partner growth', 'Ecosystem health'] },
      { id: '08', title: 'Báo cáo tài chính', items: ['P&L', 'Balance sheet', 'Cash flow', 'Unit economics', 'Burn rate'] },
      { id: '09', title: 'Báo cáo định giá', items: ['Company valuation', 'Comparable analysis', 'DCF model', 'Market multiples', 'Scenario analysis'] },
      { id: '10', title: 'Data Room', items: ['Financial documents', 'Legal documents', 'Board materials', 'Product roadmap', 'Due diligence'] },
      { id: '11', title: 'AI Investment Agent', items: ['AI phân tích tài chính', 'AI dự báo doanh thu', 'AI benchmark đối thủ', 'AI risk assessment', 'AI Q&A data room'] },
      { id: '12', title: 'Dashboard cổ đông', items: ['Executive summary', 'KPI scorecard', 'Growth dashboard', 'Ecosystem map', 'Investor updates'] },
    ],
  },

  ai: {
    id: 'ai',
    label: 'AI Agent Infrastructure',
    shortLabel: 'AI',
    icon: '🤖',
    color: '#a855f7',
    modules: [
      { id: '01', title: 'Tenant Agents', items: ['Customer Agent', 'Personal Vehicle Agent', 'Dealer Agent', 'OEM Agent', 'Bank Agent', 'Insurance Agent', 'Service Agent', 'Rescue Agent', 'Fleet Agent', 'Affiliate Agent', 'Developer Agent', 'Investment Agent'] },
      { id: '02', title: 'Core Engines', items: ['Recommendation Engine', 'Scoring Engine', 'Valuation Engine', 'Predictive Maintenance', 'Market Intelligence', 'Vehicle Economy Advisor'] },
      { id: '03', title: 'Agent Management', items: ['Agent registry', 'Agent permissions', 'Prompt templates', 'Model configuration', 'Agent monitoring'] },
      { id: '04', title: 'Training & Data', items: ['Training datasets', 'Feature store', 'Model versioning', 'A/B testing', 'Feedback loop'] },
      { id: '05', title: 'Governance', items: ['AI policies', 'Bias detection', 'Audit trail', 'Explainability', 'Compliance'] },
    ],
  },
};

const INFRASTRUCTURE = [
  { id: '01', title: 'Vehicle Economy Core', items: ['Vehicle Registry', 'Vehicle Lifecycle', 'Vehicle Economic Profile'] },
  { id: '02', title: 'Vehicle Connectivity', items: ['OBD Gateway', 'CANBUS Gateway', 'GPS Gateway', 'Telematics Gateway', 'EV Battery Gateway', 'IoT Device Management'] },
  { id: '03', title: 'Identity & Trust', items: ['Customer Identity', 'Organization Identity', 'Vehicle Identity', 'eKYC', 'eSignature', 'Contract Vault', 'Consent Management'] },
  { id: '04', title: 'Multi Tenant', items: ['OEM Tenant', 'Dealer Tenant', 'Bank Tenant', 'Insurance Tenant', 'Service Tenant', 'Developer Tenant'] },
  { id: '05', title: 'Commerce', items: ['Listing Engine', 'Quotation Engine', 'Offer Engine', 'Marketplace', 'Auction Engine', 'Lead Routing'] },
  { id: '06', title: 'Finance Infrastructure', items: ['Loan Matching', 'Leasing Matching', 'Credit Scoring', 'Embedded Finance', 'Finance Offer Engine'] },
  { id: '07', title: 'Insurance Infrastructure', items: ['Insurance Matching', 'Risk Engine', 'Usage Based Insurance', 'Claim Hub', 'Renewal Engine'] },
  { id: '08', title: 'Service Infrastructure', items: ['Booking Engine', 'Maintenance Engine', 'Work Order', 'Roadside Assistance', 'Service Recommendation'] },
  { id: '09', title: 'Payment & Settlement', items: ['Payment Connector', 'Billing', 'Subscription', 'Commission Calculation', 'Revenue Settlement'] },
  { id: '10', title: 'Data Infrastructure', items: ['Vehicle Data Lake', 'Customer Data Platform', 'Market Intelligence', 'Data API', 'Analytics Engine'] },
  { id: '11', title: 'AI Infrastructure', items: ['Customer Agent', 'Dealer Agent', 'OEM Agent', 'Recommendation Engine', 'Scoring Engine', 'Valuation Engine'] },
  { id: '12', title: 'Open Ecosystem', items: ['API Gateway', 'SDK', 'Webhook', 'Event Bus', 'Sandbox', 'Developer Portal'] },
];
